language: python

python:
  - 2.6
  - 2.7
  - 3.1
  - 3.2

install:
  - pip install -q --use-mirrors nose numpy
  - if [[ $TRAVIS_PYTHON_VERSION == '2.'* ]]; then
        pip install -q --use-mirrors PIL;
    fi
  - python setup.py install

script:
  - mkdir ../foo
  - cd ../foo
  - python ../matplotlib/tests.py
