language: python

sudo: false

cache:
  pip: true
  directories:
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
    - $HOME/.cache/matplotlib

addons:
  apt:
    packages:
      - inkscape
      - libav-tools
      - gdb
      - mencoder
      - dvipng
      - pgf
      - lmodern
      - cm-super
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-latex-recommended
      - texlive-xetex
      - graphviz
      - libgeos-dev
      - otf-freefont
#     - fonts-humor-sans
#    sources:
#      - debian-sid

env:
  global:
    - ARTIFACTS_AWS_REGION=us-east-1
    - ARTIFACTS_S3_BUCKET=matplotlib-test-results
    - secure: RgJI7BBL8aX5FTOQe7xiXqWHMxWokd6GNUWp1NUV2mRLXPb9dI0RXqZt3UJwKTAzf1z/OtlHDmEkBoTVK81E9iUxK5npwyyjhJ8yTJmwfQtQF2n51Q1Ww9p+XSLORrOzZc7kAo6Kw6FIXN1pfctgYq2bQkrwJPRx/oPR8f6hcbY=
    - secure: E7OCdqhZ+PlwJcn+Hd6ns9TDJgEUXiUNEI0wu7xjxB2vBRRIKtZMbuaZjd+iKDqCKuVOJKu0ClBUYxmgmpLicTwi34CfTUYt6D4uhrU+8hBBOn1iiK51cl/aBvlUUrqaRLVhukNEBGZcyqAjXSA/Qsnp2iELEmAfOUa92ZYo1sk=
    - secure: "dfjNqGKzQG5bu3FnDNwLG8H/C4QoieFo4PfFmZPdM2RY7WIzukwKFNT6kiDfOrpwt+2bR7FhzjOGlDECGtlGOtYPN8XuXGjhcP4a4IfakdbDfF+D3NPIpf5VlE6776k0VpvcZBTMYJKNFIMc7QPkOwjvNJ2aXyfe3hBuGlKJzQU="
    - BUILD_DOCS=false
    - NUMPY=numpy
    - OPENBLAS_NUM_THREADS=1
    - PANDAS=
    - NPROC=2
    - TEST_ARGS=--no-pep8
    - NOSE_ARGS="-j $NPROC"
    - PYTEST_ARGS="-ra --timeout=300 --durations=25 --cov-report= --cov=lib" # -n $NPROC
    - PYTHON_ARGS=
    - DELETE_FONT_CACHE=
    - USE_PYTEST=false
    #- PYTHONHASHSEED=0  # Workaround for pytest-xdist flaky colletion order
    #                    # https://github.com/pytest-dev/pytest/issues/920
    #                    # https://github.com/pytest-dev/pytest/issues/1075

matrix:
  include:
    - python: 2.7
      env: MOCK=mock NUMPY=numpy==1.7.1
    - python: 3.4
      env: PYTHON_ARGS=-OO
    - python: 3.5
      env: PANDAS=pandas NOSE_ARGS=--with-coverage DELETE_FONT_CACHE=1
    - python: 3.5
      env: RUN_FLAKE8=true SKIP_TEST=true
    - python: 3.5
      env: BUILD_DOCS=true SKIP_TEST=true
    - python: 3.5
      env: USE_PYTEST=true PANDAS=pandas DELETE_FONT_CACHE=1 TEST_ARGS=
    - python: "3.6-dev"
      env: PRE=--pre
    - python: "nightly"
      env: PRE=--pre
    - os: osx
      osx_image: xcode7.3
      language: generic  # https://github.com/travis-ci/travis-ci/issues/2312
      env: MOCK=mock NOSE_ARGS=
      cache:
        # As for now travis caches only "$HOME/.cache/pip"
        # https://docs.travis-ci.com/user/caching/#pip-cache
        pip: false
        directories:
          - $HOME/Library/Caches/pip
          # `cache` does not support `env`-like `global` so copy-paste from top
          - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
          - $HOME/.cache/matplotlib
  allow_failures:
    - python: "nightly"
 
install: source ci/travis/install.sh
script: source ci/travis/test_script.sh

after_failure:
  - |
    if [[ $BUILD_DOCS == false && $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == 'matplotlib/matplotlib' ]]; then
      gem install travis-artifacts
      cd $TRAVIS_BUILD_DIR/../tmp_test_dir
      tar cjf result_images.tar.bz2 result_images
      travis-artifacts upload --path result_images.tar.bz2
      echo https://s3.amazonaws.com/matplotlib-test-results/artifacts/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}/result_images.tar.bz2
    else
      echo "The result images will only be uploaded if they are on the matplotlib/matplotlib repo - this is for security reasons to prevent arbitrary PRs echoing security details."
    fi

after_success:
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == 'matplotlib/matplotlib' && $BUILD_DOCS == true && $TRAVIS_BRANCH == 'master' ]]; then
      cd $TRAVIS_BUILD_DIR
      echo "Uploading documentation"
      openssl aes-256-cbc -K $encrypted_cc802e084cd0_key -iv $encrypted_cc802e084cd0_iv -in ci/travis/matplotlibDeployKey.enc -out ci/travis/matplotlibDeployKey -d
      eval `ssh-agent -s`
      chmod 600 ci/travis/matplotlibDeployKey
      ssh-add ci/travis/matplotlibDeployKey
      cd ..
      git clone git@github.com:matplotlib/devdocs.git
      cd devdocs
      git checkout --orphan gh-pages
      git reset --hard first_commit
      cp -R ../matplotlib/doc/build/html/. .
      touch .nojekyll
      git config --global user.email "MatplotlibTravisBot@nomail"
      git config --global user.name "MatplotlibTravisBot"
      git config --global push.default simple
      git add .
      git commit -m "Docs build of $TRAVIS_COMMIT"
      git push --set-upstream origin gh-pages --force
    else
      echo "Will only deploy docs build from matplotlib master branch"
    fi
    if [[ $NOSE_ARGS =~ "--with-coverage" || $USE_PYTEST == true ]]; then
      coveralls
      bash <(curl -s https://codecov.io/bash)
    fi
