language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

install:
  - pip -q install --use-mirrors nose numpy
  - if [[ $TRAVIS_PYTHON_VERSION == '2.'* ]]; then pip -q install --use-mirrors PIL; fi
  - sudo apt-get -qq update && sudo apt-get -qq install inkscape
  - python setup.py install

script:
  - mkdir ../tmp_test_dir
  - cd ../tmp_test_dir
  - python ../matplotlib/tests.py -sv
