language: python

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33

install:
  - pip install -q --use-mirrors tox
  - sudo apt-get update && sudo apt-get -qq install inkscape

script:
  # The number of processes is hardcoded, because using too many causes the
  # Travis VM to run out of memory (since so many copies of inkscape and
  # ghostscript are running at the same time).
  - echo Testing using 8 processes
  - tox -- --processes=8 --process-timeout=300
