language: python

python:
  - 2.6
  - 2.7
  - 3.1
  - 3.2

install:
  - pip install --use-mirrors nose numpy > /dev/null
  - if [[ $TRAVIS_PYTHON_VERSION == '2.'* ]]; then pip install --use-mirrors PIL > /dev/null; fi
  - python setup.py -q install

script:
  - mkdir ../foo
  - cd ../foo
  - python ../matplotlib/tests.py
