language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

install:
  - pip -q install --use-mirrors nose python-dateutil numpy
  # This is a workaround to install the latest versions of pyparsing,
  # which are not yet available on PyPI
  - 'if [ ${TRAVIS_PYTHON_VERSION:0:1} == "3" ]; then pip -q install http://sourceforge.net/projects/pyparsing/files/pyparsing/pyparsing-2.0.0/pyparsing-2.0.0.tar.gz; fi'
  - 'if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then pip -q install http://sourceforge.net/projects/pyparsing/files/pyparsing/pyparsing-1.5.7/pyparsing-1.5.7.tar.gz; fi'
  - if [[ $TRAVIS_PYTHON_VERSION == '2.'* ]]; then pip -q install --use-mirrors PIL; fi
  - sudo apt-get update && sudo apt-get -qq install inkscape
  - python setup.py install

script:
  - mkdir ../tmp_test_dir
  - cd ../tmp_test_dir
  - echo Testing using $(nproc) processes
  - python ../matplotlib/tests.py -sv --processes=$(nproc) --process-timeout=300
