# With infos from
# http://tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/
# https://packaging.python.org/en/latest/appveyor/
# https://github.com/rmcgibbo/python-appveyor-conda-example

# Backslashes in quotes need to be escaped: \ -> "\\"

environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C obvci_appveyor_python_build_env.cmd"
    CONDA_INSTALL_LOCN: "C:\\conda"
    # Workaround for https://github.com/conda/conda-build/issues/636
    PYTHONIOENCODING: "UTF-8"

  matrix:
    # for testing purpose: numpy 1.8 on py2.7, for the rest use 1.10/latest
    - TARGET_ARCH: "x86"
      CONDA_PY: "27"
      CONDA_NPY: "18"
      PYTHON_VERSION: "2.7"
    - TARGET_ARCH: "x64"
      CONDA_PY: "27"
      CONDA_NPY: "18"
      PYTHON_VERSION: "2.7"
    - TARGET_ARCH: "x64"
      CONDA_PY: "34"
      CONDA_NPY: "110"
      PYTHON_VERSION: "3.4"
    - TARGET_ARCH: "x64"
      CONDA_PY: "35"
      CONDA_NPY: "110"
      PYTHON_VERSION: "3.5"


# We always use a 64-bit machine, but can build x86 distributions
# with the PYTHON_ARCH variable (which is used by CMD_IN_ENV).
platform:
    - x64

# all our python builds have to happen in tests_script...
build: false

init:
  - "ECHO %PYTHON_VERSION% %CONDA_INSTALL_LOCN%"

install:
  - appveyor DownloadFile "https://raw.githubusercontent.com/pelson/Obvious-CI/master/bootstrap-obvious-ci-and-miniconda.py"
  - cmd: python bootstrap-obvious-ci-and-miniconda.py %CONDA_INSTALL_LOCN% %TARGET_ARCH% %CONDA_PY:~0,1% --without-obvci
  - cmd: set PATH=%PATH%;%CONDA_INSTALL_LOCN%;%CONDA_INSTALL_LOCN%\scripts
  - cmd: set PYTHONUNBUFFERED=1
  - cmd: conda install -c http://conda.anaconda.org/pelson/channel/development --yes --quiet obvious-ci
  - cmd: obvci_install_conda_build_tools.py
  - cmd: conda config --set show_channel_urls yes
  # for msinttypes
  - cmd: conda config --add channels conda-forge
  # this is now the downloaded conda...
  - conda info -a
  # same things as the requirements in ci/conda_recipe/meta.yaml
  - cmd: conda create -y -q -n test-environment python=%PYTHON_VERSION% pip setuptools numpy python-dateutil freetype=2.5 msinttypes tk pyparsing pytz tornado libpng zlib pyqt cycler nose mock
  - activate test-environment
  - cmd: echo %PYTHON_VERSION% %TARGET_ARCH%
  - cmd: IF %PYTHON_VERSION% == 2.7 conda install -y functools32
  # This is needed for the installer to find the dlls...
  - set LIBRARY_LIB=%CONDA_DEFAULT_ENV%\Library\lib
  - cmd: 'mkdir lib || cmd /c "exit /b 0"'
  - copy %LIBRARY_LIB%\zlibstatic.lib lib\z.lib
  - copy %LIBRARY_LIB%\libpng_static.lib lib\png.lib
  - set MPLBASEDIRLIST=%CONDA_DEFAULT_ENV%\Library\;.
  # enables the local freetype build
  - copy ci\travis\setup.cfg .
  # There is no 2.7 64bit freetype build configuration...
  - cmd: IF %PYTHON_VERSION% == 2.7 (IF %TARGET_ARCH% == x64 (del setup.cfg))
  # Show the installed packages + versions
  - conda list

test_script:
  # Now build the thing..
  - '%CMD_IN_ENV% python setup.py develop'
  # tests
  # for now, just let them pass to get the after_test parts...
  - python tests.py || cmd /c "exit /b 0"

after_test:
  # After the tests were a success, build packages (wheels and conda)

  # There is a bug in wheels which prevents building wheels when the package uses namespaces
  - cmd: '%CMD_IN_ENV% python setup.py bdist_wheel'
  # Note also that our setup.py script, which is called by conda-build, writes
  # a __conda_version__.txt file, so the version number on the binary package
  # is set dynamically. This unfortunately means that conda build --output
  # doesn't really work.
  - cmd: '%CMD_IN_ENV% conda config --get channels'
  - cmd: '%CMD_IN_ENV% conda build .\ci\conda_recipe'
  # Move the conda package into the dist directory, to register it
  # as an "artifact" for Appveyor.
  - cmd: 'copy /Y %CONDA_INSTALL_LOCN%\conda-bld\win-32\*.bz2 dist || cmd /c "exit /b 0"'
  - cmd: 'copy /Y %CONDA_INSTALL_LOCN%\conda-bld\win-64\*.bz2 dist || cmd /c "exit /b 0"'
  - cmd: dir .\dist\

artifacts:
  - path: dist\*
    name: packages

  - path: result_images\*
    name: result_images
    type: zip

on_failure:
  - 7z a result_images.zip result_images\ >NUL:
  - appveyor PushArtifact result_images.zip
