[project]
name = "matplotlib"
authors = [
  {email = "matplotlib-users@python.org"},
  {name = "John D. Hunter, Michael Droettboom"}
]
description = "Python plotting package"
readme = "README.md"
license = { file = "LICENSE/LICENSE" }
dynamic = ["version", "optional-dependencies"]
classifiers=[
    'Development Status :: 5 - Production/Stable',
    'Framework :: Matplotlib',
    'Intended Audience :: Science/Research',
    'Intended Audience :: Education',
    'License :: OSI Approved :: Python Software Foundation License',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Topic :: Scientific/Engineering :: Visualization',
]

# When updating the list of dependencies, add an api_changes/development
# entry and also update the following places:
# - lib/matplotlib/__init__.py (matplotlib._check_versions())
# - requirements/testing/minver.txt
# - doc/devel/dependencies.rst
# - .github/workflows/tests.yml
# - environment.yml
dependencies = [
    "contourpy>=1.0.1",
    "cycler>=0.10",
    "fonttools>=4.22.0",
    "kiwisolver>=1.0.1",
    "numpy>=1.21",
    "packaging>=20.0",
    "pillow>=6.2.0",
    "pyparsing>=2.3.1",
    "python-dateutil>=2.7",
    "setuptools_scm>=7.0"
]
requires-python = ">=3.9"

[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "certifi>=2020.06.20",
    "oldest-supported-numpy",
    "pybind11>=2.6",
    "setuptools_scm>=7",
]

[tool.isort]
known_mpltoolkits = "mpl_toolkits"
known_pydata = "numpy, matplotlib.pyplot"
known_firstparty = "matplotlib"
sections = "FUTURE,STDLIB,THIRDPARTY,PYDATA,FIRSTPARTY,MPLTOOLKITS,LOCALFOLDER"
no_lines_before = "MPLTOOLKITS"
force_sort_within_sections = true

[tool.setuptools]
platforms = ["any"]
py-modules = ["pylab"]
namespace-packages = ["mpl_toolkits"]

[tool.setuptools.packages.find]
where = ["lib"]
include = ["matplotlib*", "mpl_toolkits*"]
exclude = [
    "matplotlib.tests*",
    "mpl_toolkits.axes_grid1.tests*",
    "mpl_toolkits.axisartist.tests*",
    "mpl_toolkits.mplot3d.tests*"
]
namespaces = false

[tool.setuptools.exclude-package-data]
"*" = ["*.png", "*.svg"]

[tool.setuptools_scm]
version_scheme = "release-branch-semver"
local_scheme = "node-and-date"
write_to = "lib/matplotlib/_version.py"
parentdir_prefix_version = "matplotlib-"
fallback_version = "0.0+UNKNOWN"

[project.urls]
'Homepage' = 'https://matplotlib.org'
'Download' = 'https://matplotlib.org/stable/users/installing/index.html'
'Documentation' = 'https://matplotlib.org'
'Source Code' = 'https://github.com/matplotlib/matplotlib'
'Bug Tracker' = 'https://github.com/matplotlib/matplotlib/issues'
'Forum' = 'https://discourse.matplotlib.org/'
'Donate' = 'https://numfocus.org/donate-to-matplotlib'
