
[tool.towncrier]
    package = "matplotlib"
    filename = "doc/CHANGELOG.rst"
    directory = "changelog/"
    issue_format = "`#{issue} <https://github.com/matplotlib/matplotlib/pull/{issue}>`__"

    [[tool.towncrier.type]]
        directory = "breaking"
        name = "Breaking API changes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bug fixes"
        showcontent = true

    [[tool.towncrier.type]]
      directory = "removal"
      name = "Removals"
      showcontent = true

    [[tool.towncrier.type]]
      directory = "feature"
      name = "New features"
      showcontent = true
