name: Build CI wheels

on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+.x
    tags:
      - v*
  schedule:
    # every Sunday at midnight, builds master and uploads to 
    # https://anaconda.org/scipy-wheels-nightly/
    - cron: '0 0 * * 0'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
          

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.6.3

      - name: Copy setup.cfg to configure wheel
        run: |
          cp setup.cfg.template setup.cfg

      - name: Build wheels for CPython 3.9
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp39-*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2010
          CIBW_MANYLINUX_I686_IMAGE: manylinux2010
          CIBW_BEFORE_BUILD: pip install certifi numpy==1.19.3
          MPL_DISABLE_FH4: "yes"

      - name: Build wheels for CPython
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp3?-*"
          CIBW_SKIP: "cp35-* cp36-* cp39-*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux1
          CIBW_MANYLINUX_I686_IMAGE: manylinux1
          CIBW_BEFORE_BUILD: pip install certifi numpy==1.16
          MPL_DISABLE_FH4: "yes"

      - name: Build wheels for CPython 3.6
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp36-*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux1
          CIBW_MANYLINUX_I686_IMAGE: manylinux1
          CIBW_BEFORE_BUILD: pip install certifi numpy==1.16
          MPL_DISABLE_FH4: "yes"
        if: >
          startsWith(github.ref, 'refs/heads/v3.3') ||
          startsWith(github.ref, 'refs/tags/v3.3')

      - name: Build wheels for PyPy3.7
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "pp37-*"
          CIBW_BEFORE_BUILD: pip install certifi numpy==1.16
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2010
          CIBW_MANYLINUX_I686_IMAGE: manylinux2010

      - name: Validate that LICENSE files are included in wheels
        run: |
          python ./ci/check_wheel_licenses.py

      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./dist/*.whl

    - name: Set token
      if: github.event_name == "schedule"
      run: |
        echo "TOKEN=${{ secrets.SCIPY_WHEELS_NIGHTLY_ACCESS }}" >> $GITHUB_ENV;
        echo "ANACONDA_ORG=https://anaconda.org/scipy-wheels-nightly" >> $GITHUB_ENV;

    - name: Upload weekly wheels
      if: env.TOKEN
      run: |
        set -ex
        pip install git+https://github.com/Anaconda-Server/anaconda-client;
        # The first -t option refers to the token, the second is the "type"
        # option to the "upload" command
        anaconda -t  ${TOKEN} upload \
        --no-progress --force -u $ANACONDA_ORG \
        ./dist/*.whl;
