name: Add comment on good first issues
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'Good first issue'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Please see https://matplotlib.org/stable/devel/index for more information if needed.
            We do not assign issues, but unless there is a PR for this issue already, feel free
            to just start working on it. Do not hesitate to ask if something needs clarification.
